Exclude test2 pack from index
StackStorm-Exchange/stackstorm-test2 pull request #8
Opened 2021-02-10 16:26 UTC by cognifloyd

This allows us to use full pack CI in this test pack without actually
adding it to the index.

Depends on StackStorm-Exchange/ci#108

2021-02-10 16:33 UTC, armab requested changes
Please just update the deploy branch back to `master` and it'll make it non-deploy as before.

2021-02-10 16:36 UTC, cognifloyd commented
I disagree.
We need the weekly job to run to ensure the PAT continues to be active.
Also, to be a good test, everything should run except for pushing to the index.

2021-02-10 17:01 UTC, arm4b commented
Because this repo shouldn't be part of the Exchange index, it doesn't need to run the deploy step at all and so no token or regeneration required.

2021-02-10 17:04 UTC, cognifloyd commented
I could have done a lot of my testing with the `test` or `test2` pack if they'd actually been up-to-date. As is, I ended up using several other packs to test CI changes. Please, we need to be able to use test packs to test CI changes, including changes to the `deploy` step.

2021-02-10 18:26 UTC, cognifloyd commented
In other words, I wanted to use `test` and `test2` for the purpose listed in the readme:
https://github.com/StackStorm-Exchange/stackstorm-test2/blob/a82739da92113b401d09192743cf2eb7296e2b7b/README.md#L3

To test changes to the pack CI system itself.

2021-02-12 01:09 UTC, cognifloyd commented
Closing this in favor of a variable added via CircleCI itself.
https://github.com/StackStorm-Exchange/ci/pull/108#issuecomment-777746129

2021-02-12 01:09 UTC, closed without merging